"""initial_full_schema

Revision ID: bb9d7873e725
Revises: 
Create Date: 2026-04-04 13:32:10.067320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb9d7873e725'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_category_registry',
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('value_type', sa.String(length=20), server_default='numeric', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('category')
    )
    op.create_table('metric_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('agg_strategy', sa.String(length=50), server_default='average', nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('calculation_logic', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'metric_name', name='uq_metric_cat_name')
    )
    op.create_index('idx_metric_def_cat', 'metric_definitions', ['category'], unique=False)
    op.create_table('task_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processed_date', sa.Date(), nullable=True),
    sa.Column('records_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('daily_metrics_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('agg_window', sa.String(length=20), server_default='1d', nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'bucket_start', 'category', 'metric_name', 'agg_window', name='uq_summary_user_bucket_metric')
    )
    op.create_index('idx_summary_user_query', 'daily_metrics_summary', ['user_id', 'category', 'record_date'], unique=False)
    op.create_table('user_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_name', sa.String(length=50), nullable=True),
    sa.Column('scopes', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_key_lookup', 'user_api_keys', ['api_key_hash'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index(op.f('ix_user_api_keys_api_key_hash'), 'user_api_keys', ['api_key_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_api_keys_api_key_hash'), table_name='user_api_keys')
    op.drop_index('idx_api_key_lookup', table_name='user_api_keys', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('user_api_keys')
    op.drop_index('idx_summary_user_query', table_name='daily_metrics_summary')
    op.drop_table('daily_metrics_summary')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('task_execution_logs')
    op.drop_index('idx_metric_def_cat', table_name='metric_definitions')
    op.drop_table('metric_definitions')
    op.drop_table('data_category_registry')
    # ### end Alembic commands ###
